added success counter metrics in MonitorContentTranslationService
racker/salus-telemetry-monitor-management pull request #207
Opened 2020-09-08 08:39 UTC by shabd67

# Resolves

[SALUS-1008](https://jira.rax.io/browse/SALUS-1008)

# What

Adding Success/Failure Metrics count to be displayed onto Grafana

2020-09-08 15:02 UTC, itzg reviewed
@jjbuchan @GeorgeJahad @harageth , seeing these metrics in context of success vs failure makes me wondering if we've been "inverting" our usage of metric names and discriminating tags. Or more specifically, we've been perhaps over-using discriminating tags. What we have tended to do actually looks similar to the "Bad approach" [shown in the Micrometer docs](https://micrometer.io/docs/concepts#_tag_naming).

Having explored several TSDBs lately I am liking the verbosity and expressiveness of naming conventions like [Prometheus'](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels). Micrometer even points to [this Graphite article](https://matt.aimonetti.net/posts/2013-06-practical-guide-to-graphite-monitoring/) for advice on naming conventions.

2020-09-09 11:39 UTC, shabd67 commented
Sample Metric:

[
    "service_operations_succeeded,app=salus-telemetry-monitor-management,host=MCR872MD6M,metric_type=counter,operation=createMonitor"
],
[
    "service_operations_succeeded,app=salus-telemetry-monitor-management,host=MCR872MD6M,metric_type=counter,operation=removeMonitor"
],
[
    "service_operations_succeeded,app=salus-telemetry-monitor-management,host=MCR872MD6M,metric_type=counter,operation=updateMonitor"
]

2020-09-09 15:02 UTC, itzg reviewed
A few comments so far

2020-09-09 15:02 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorContentTranslationService.java
> +      translateMonitorContentFailed.tags("operation", "monitorContentTranslate").register(meterRegistry).increment();
With comment above
```suggestion
      translateMonitorContentFailed.tags("operation", "translate").register(meterRegistry).increment();
```

2020-09-09 15:11 UTC, shabd67 commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorContentTranslationService.java
> +    translateMonitorContentFailed  = Counter.builder(MetricsName.SERVICE_OPERATION_FAILED_METRIC_NAME);
yes, that would be good and efficient for debugging as well.

2020-09-09 15:31 UTC, itzg reviewed
A few more comments that you can use as a pattern for the other files.

2020-09-09 15:31 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
> +    orphanedBoundMonitorRemoved = Counter.builder("orphaned");
It looks like this one can be created like normal rather than using a builder; however, the consistency of builders makes sense too.

2020-09-09 15:31 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
> +    if (meterRegistry != null) {
When would `meterRegistry` be null?

2020-09-09 15:31 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
> +    createMonitorSuccess.tags("operation","createMonitor","objectType","policyMonitor").register(meterRegistry).increment();
Assuming the existence of a "service" tag and then the "objectType" here, then similarly "operation" can be just "create".

2020-09-09 15:31 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
> +          createMonitorFailed.tags("operation","boundMonitorSave").register(meterRegistry).increment();
Metrics on every bound monitor operation could get inefficient and tedious to cover in all the places. There's a version of `increment` that takes a value to increment in total.

2020-09-09 15:31 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
> +    createMonitorSuccess.tags("operation","updateMonitor").register(meterRegistry).increment();
To be consistent with others, should include an "objectType". And with that "operation" can be simply "update".

2020-09-09 15:31 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
> +        orphanedBoundMonitorRemoved.tags("objectType", "boundMonitor").register(meterRegistry).increment();
For this particular metric, the "objectType" doesn't seem to be necessary.

2020-09-09 15:31 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
> +          createMonitorFailed.tags("operation","renderMonitorTemplate").register(meterRegistry).increment();
On failure metrics it would be good to have a "reason" or "exception" tag. An "exception" tag would be logical to add and can be simply the name of the caught exception, like "InvalidTemplateException" in this case or `e.getClass().getSimpleName()` to save typing out specific names each time.

2020-09-09 15:41 UTC, shabd67 commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
> +    orphanedBoundMonitorRemoved = Counter.builder("orphaned");
now, it will be look like:
`createMonitorSuccess = Counter.builder(MetricsName.SERVICE_OPERATION_SUCCEEDED_METRIC_NAME).tag("service","MonitorManagement");
createMonitorFailed  = Counter.builder(MetricsName.SERVICE_OPERATION_FAILED_METRIC_NAME).tag("service","MonitorManagement");
orphanedBoundMonitorRemoved = Counter.builder("orphaned").tag("service","MonitorManagement");`

2020-09-09 16:18 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
> +    orphanedBoundMonitorRemoved = Counter.builder("orphaned");
👍

2020-09-09 18:13 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
> +    orphanedBoundMonitorRemoved = Counter.builder("orphaned");
@shabd67 fyi, three ` form a multi-line code-block.  You can see by adding two more at the beginning and end of your example.  The functionality of that in github and slack is the same.
```
for example this was started with ``` and ended with ```
```

2020-09-09 18:16 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
> +          createMonitorFailed.tags("operation","renderMonitorTemplate").register(meterRegistry).increment();
Agreed that metrics for exception types is good.  Log messages should handle any more detail than that.

2020-09-09 18:18 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
> +    if (meterRegistry != null) {
I don't think it should.  You may have copied this from the KafkaErrorConfig?  If so, the only reason it needed this check is because it relies on an `Optional` autowired dependency.  Any of our services should not have that same problem as they are the ones that are initializing that dependency.

2020-09-09 18:20 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorContentTranslationService.java
> +    translateMonitorContentFailed  = Counter.builder(MetricsName.SERVICE_OPERATION_FAILED_METRIC_NAME);
I'd shorten these to remove the trailing `_METRIC_NAME`.  The class being called `MetricsName` helps provide enough context.

2020-09-09 18:21 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorContentTranslationService.java
> +    translateMonitorContentFailed  = Counter.builder(MetricsName.SERVICE_OPERATION_FAILED_METRIC_NAME);
and I guess a nit on that... I'd prefer `MetricName` or `MetricNames`.  Currently it feels like the `s` is in the wrong place :)

2020-09-09 18:28 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorContentTranslationService.java
> +    translateMonitorContentSuccess.tags("operation", "CreateMonitorTranslationOperator").register(meterRegistry).increment();
I'm good with that.  We do lose the natural grouping based on individual tags if `create` means a variety of things across services but the benefit of grouping by a selection of services and having simpler names outweighs the crossover that may happen imo.

2020-09-09 18:34 UTC, jjbuchan reviewed
I agree with Geoff's points and think this is a great start.  The most important thing is producing metrics to begin with.  As time goes on and we're looking at graphs more this'll help make it easy to tweak things as we need and better see what might be missing.

2020-09-09 18:34 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/monitor_management/services/TestMonitorService.java
> +        testMonitorFailed.tags("operation", "performTestMonitor").register(meterRegistry).increment();
Just noting that all these could use the previously mentioned exception logging too.

2020-09-10 07:37 UTC, shabd67 commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
> +    if (meterRegistry != null) {
yes, it was copied from there and post that, I just forgot to remove that piece of code.

2020-09-10 07:58 UTC, shabd67 commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorContentTranslationService.java
> +    translateMonitorContentSuccess.tags("operation", "CreateMonitorTranslationOperator").register(meterRegistry).increment();
I think `"operation", "create","objectType","monitorTranslationOperator"` as tags would be better as it demonstrates that the operation type is "create" and objectType which has been created is "monitorTranslationOperator". @jjbuchan and @itzg , your views on it?

2020-09-10 08:05 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorContentTranslationService.java
> +    translateMonitorContentSuccess.tags("operation", "CreateMonitorTranslationOperator").register(meterRegistry).increment();
I do like the idea of including a `service` tag for each of these.  Would you include that in addition to `objectType`?

I'd assume most services would only have one `objectType` but some may have multiple?

2020-09-10 08:10 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorContentTranslationService.java
> +    translateMonitorContentSuccess.tags("operation", "CreateMonitorTranslationOperator").register(meterRegistry).increment();
...although saying that if there is a common tag that includes the application name (such as monitoring-management) then maybe the service tag is essentially redundant.

I'm willing to +1 either of the options suggested.  I really do think once we have the metrics out there and are using them it'll be easier to determine whether we need to tweak them.  In reality, either option will most likely work fine.

2020-09-10 08:27 UTC, shabd67 commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
> +          createMonitorFailed.tags("operation","renderMonitorTemplate").register(meterRegistry).increment();
instead of having name of caught exception, I think it's better to have toString() of caught exception as that would cover exception class name along with exception message.

2020-09-10 10:43 UTC, shabd67 commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorContentTranslationService.java
> +    translateMonitorContentFailed  = Counter.builder(MetricsName.SERVICE_OPERATION_FAILED_METRIC_NAME);
Noted.

2020-09-10 10:49 UTC, shabd67 commented
@jjbuchan / @itzg , if you notice I have written metrics generation logic to all the service classes which contains main business logic like MonitorManagement, MonitorContentTranslationService, TestMonitorService and ZoneManagement only. Do I need to write the same logic for other service classes like Kafka producer and consumer classes, ZoneResolver, MonitorContentRenderer ?

2020-09-10 14:14 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorContentTranslationService.java
> +    translateMonitorContentSuccess.tags("operation", "CreateMonitorTranslationOperator").register(meterRegistry).increment();
I'd recommend including "service" since I was thinking that would be one level finer grained than "app" to indicate which Spring **service** specifically did the operation.

So, looks like we've arrived at three standard tags (for most cases): `operation`, `service`, `objectType`

2020-09-10 14:17 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
> +          createMonitorFailed.tags("operation","renderMonitorTemplate").register(meterRegistry).increment();
Using the `toString` value is dangerous. Tag value cardinality needs to be well bounded since the number of metric names and unique combination of tag key-values drives the number of metrics our TSDB needs to track. Right now in UMB we're tracking about 5 million metric-sets...which is already a lot :)

2020-09-10 14:22 UTC, shabd67 commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorContentTranslationService.java
> +    translateMonitorContentSuccess.tags("operation", "CreateMonitorTranslationOperator").register(meterRegistry).increment();
while for Success cases: 
`[
                            1599733529204000000,
                            "salus-telemetry-monitor-management",
                            null,
                            "MCR872MD6M",
                            "counter",
                            "monitor",
                            "create",
                            "MonitorManagement",
                            1
                        ],
                        [
                            1599733529205000000,
                            "salus-telemetry-monitor-management",
                            null,
                            "MCR872MD6M",
                            "counter",
                            "monitor",
                            "remove",
                            "MonitorManagement",
                            1
                        ]`

2020-09-10 14:29 UTC, shabd67 commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
> +          createMonitorFailed.tags("operation","renderMonitorTemplate").register(meterRegistry).increment();
yes, that might not be helpful then.

2020-09-10 14:32 UTC, itzg reviewed
I like the "operation", "service", "objectType" changes.

@jjbuchan and others, I'd like to get your thought on the comment I left below.

(I'm going to pause my review until we ponder the error metric strategy.)

2020-09-10 16:19 UTC, shabd67 commented
@itzg / @jjbuchan , will change lambda and functional optional usage in MonitorManagement once you approve current RestExceptionHandler approach.

2020-09-10 17:58 UTC, itzg reviewed
I like this approach with RestExceptionHandler with servlet path added. 

I just confirmed that @jjbuchan  had already added [similar error metric handling in our kafka listener error handler](https://github.com/racker/salus-common/blob/bcf53c9f841961c10fac4c6a88bf0679b2ff9fa0/src/main/java/com/rackspace/salus/common/messaging/KafkaErrorConfig.java#L75)...now that I think about it, that's probably the counter builder example that was used :)

2020-09-10 17:58 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/web/controller/RestExceptionHandler.java
> +        monitorManagementErrorCounter.tags("exception","NotFoundException").register(meterRegistry).increment();
I think it would be good to include `request.getServletPath()` as a tagged value similar to what Spring MVC metrics do. That way we will have a pretty good indication of what logs to find when debugging.

2020-09-10 17:58 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/web/controller/RestExceptionHandler.java
> +        monitorManagementErrorCounter.tags("exception","NotFoundException").register(meterRegistry).increment();
Can use `e.getClass().getSimpleName()` here to simplify copy-paste across methods and modules.

2020-09-11 16:22 UTC, itzg requested changes
Just small changes now

2020-09-11 16:22 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/services/TestMonitorService.java
>                      .format("An unexpected internal error occurred: %s", throwable.getMessage())));
Would be good to increment an error counter here

2020-09-11 16:22 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/services/TestMonitorService.java
> +    return leastLoadedOptional.get().getEnvoyId();
Can be reverted

2020-09-11 16:22 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/services/ZoneManagement.java
> +      zoneManagementSuccess.tags("operation","removeAll","objectType","zone").register(meterRegistry).increment();
To align with others
```suggestion
      zoneManagementSuccess.tags("operation","removeAll","objectType","privateZone").register(meterRegistry).increment();
```

2020-09-14 13:55 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorContentTranslationService.java
> +    translateMonitorContentSuccess.tags(MetricTags.OPERATION_METRIC_TAG, "create",MetricTags.OBJECT_TYPE_METRIC_TAG,"monitorTranslationOperator").register(meterRegistry).increment();
Were you going to go ahead and create a common metric tag value for "create"?

2020-09-14 13:59 UTC, shabd67 commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorContentTranslationService.java
> +    translateMonitorContentSuccess.tags(MetricTags.OPERATION_METRIC_TAG, "create",MetricTags.OBJECT_TYPE_METRIC_TAG,"monitorTranslationOperator").register(meterRegistry).increment();
yes

2020-09-14 14:09 UTC, itzg requested changes
Just a couple more spots.

2020-09-14 14:09 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
> -          invalidTemplateErrors.increment();
This one needs `invalidTemplateErrors` incremented

2020-09-14 14:09 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
> -          orphanedPolicyMonitors.increment();
This one needs `orphanedBoundMonitorRemoved` incremented

2020-09-14 14:09 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorContentTranslationService.java
> -            monitorTranslateErrors.increment();
Just noticed this one needs a specific error counter added back.

2020-09-14 14:09 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/services/TestMonitorService.java
>                      .format("An unexpected internal error occurred: %s", throwable.getMessage())));
Still would like a specific error counter here

2020-09-14 14:09 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/web/controller/RestExceptionHandler.java
> +        monitorManagementErrorCounter.tags(MetricTags.URI_METRIC_TAG,request.getServletPath(),
Can you double check that the servlet path includes just the path variables and not specific values, like the actual tenant ID?

2020-09-14 14:33 UTC, shabd67 commented on src/main/java/com/rackspace/salus/monitor_management/web/controller/RestExceptionHandler.java
> +        monitorManagementErrorCounter.tags(MetricTags.URI_METRIC_TAG,request.getServletPath(),
yes, it like `1600093980109000000 salus-telemetry-monitor-management NotFoundException MCR872MD6M counter     /api/tenant/aaaaaa/monitors/38633258-701b-46ee-b88b-a0804d826dfa 2`

2020-09-14 14:43 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/web/controller/RestExceptionHandler.java
> +        monitorManagementErrorCounter.tags(MetricTags.URI_METRIC_TAG,request.getServletPath(),
Uh oh, that's not good. I wonder which field of the request has the equivalent of the `@RequestMapping` path?

2020-09-14 14:46 UTC, shabd67 commented on src/main/java/com/rackspace/salus/monitor_management/web/controller/RestExceptionHandler.java
> +        monitorManagementErrorCounter.tags(MetricTags.URI_METRIC_TAG,request.getServletPath(),
its like 

> time                app                                exception         host       metric_type uri                                                              value
----                ---                                ---------         ----       ----------- ---                                                              -----
1600093980109000000 salus-telemetry-monitor-management NotFoundException MCR872MD6M counter     /api/tenant/aaaaaa/monitors/38633258-701b-46ee-b88b-a0804d826dfa 2

2020-09-14 14:49 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/web/controller/RestExceptionHandler.java
> +        monitorManagementErrorCounter.tags(MetricTags.URI_METRIC_TAG,request.getServletPath(),
Yes, I understand that. I would like the path to be `/tenant/{tenantId}/monitors/{uuid}` to avoid an explosion of distinct tag values.

2020-09-14 14:51 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/web/controller/RestExceptionHandler.java
> +        monitorManagementErrorCounter.tags(MetricTags.URI_METRIC_TAG,request.getServletPath(),
From https://github.com/spring-projects/spring-boot/blob/76bf89ecd2db8031658cd716ea13206c738dd7f6/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/metrics/web/servlet/WebMvcTags.java#L156 it looks like `request.getAttribute(HandlerMapping.BEST_MATCHING_PATTERN_ATTRIBUTE)` will give that

2020-09-14 14:58 UTC, shabd67 commented on src/main/java/com/rackspace/salus/monitor_management/web/controller/RestExceptionHandler.java
> +        monitorManagementErrorCounter.tags(MetricTags.URI_METRIC_TAG,request.getServletPath(),
yes, its working fine. thank you

2020-09-14 14:58 UTC, itzg requested changes
Just needs the templated URL path mentioned in https://github.com/racker/salus-telemetry-monitor-management/pull/207#discussion_r487994017

2020-09-14 15:00 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/web/controller/RestExceptionHandler.java
> +        monitorManagementErrorCounter.tags(MetricTags.URI_METRIC_TAG,request.getAttribute(HandlerMapping.BEST_MATCHING_PATTERN_ATTRIBUTE).toString(),
Did this work as expected?

2020-09-14 15:01 UTC, shabd67 commented on src/main/java/com/rackspace/salus/monitor_management/web/controller/RestExceptionHandler.java
> +        monitorManagementErrorCounter.tags(MetricTags.URI_METRIC_TAG,request.getAttribute(HandlerMapping.BEST_MATCHING_PATTERN_ATTRIBUTE).toString(),
yes. 

> 1600095461417000000 salus-telemetry-monitor-management NotFoundException MCR872MD6M counter     /api/tenant/{tenantId}/monitors/{uuid} 2

2020-09-14 15:14 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/web/controller/RestExceptionHandler.java
> +        monitorManagementErrorCounter.tags(MetricTags.URI_METRIC_TAG,request.getAttribute(HandlerMapping.BEST_MATCHING_PATTERN_ATTRIBUTE).toString(),
Excellent!

2020-09-14 15:15 UTC, itzg submitted a review, later dismissed

2020-09-15 14:17 UTC, itzg requested changes
Use SimpleMeterRegistry since it is much...simpler.

2020-09-15 14:17 UTC, itzg commented on src/test/java/com/rackspace/salus/monitor_management/services/MonitorManagementExcludeResourceIdsTest.java
> +@Import({MetricsAutoConfiguration.class, CompositeMeterRegistryAutoConfiguration.class})
I usually just import `SimpleMeterRegistry` to get both a real instance and not all of the auto-configured exports that we might happen to have in our apps (however, they're disabled by default).
```suggestion
@Import({SimpleMeterRegistry.class})
```

2020-09-15 14:37 UTC, itzg requested changes
Just one super small change.

2020-09-15 14:37 UTC, itzg commented on src/test/java/com/rackspace/salus/monitor_management/services/TestMonitorServiceTest.java
> +  @Import({TestMonitorService.class, MetricsAutoConfiguration.class, CompositeMeterRegistryAutoConfiguration.class})
This one had the inner config class, which threw off your pattern :)
```suggestion
  @Import({TestMonitorService.class, SimpleMeterRegistry.class})
```

2020-09-15 14:37 UTC, itzg commented on src/test/java/com/rackspace/salus/monitor_management/services/TestMonitorServiceTest.java
> +@Import({SimpleMeterRegistry.class})
Remove this one and change `@Import` below.

2020-09-15 15:00 UTC, itzg approved these changes

2020-09-15 15:20 UTC, merged