Upload swagger json alongside salus_www HTML API docs
racker/salus-telemetry-monitor-management pull request #211
Opened 2020-10-01 17:04 UTC by shabd67

# Resolves

[SALUS-1019](https://jira.rax.io/browse/SALUS-1019)

# What

Upload swagger json alongside salus_www HTML API docs

# Depends on

https://github.com/racker/salus-tools/pull/42

2020-10-01 17:05 UTC, shabd67 commented
Once approved here, will change accordingly in other apps and raise PR.

2020-10-01 17:11 UTC, itzg requested changes

2020-10-01 17:11 UTC, itzg commented on pom.xml
> +              <inputSpec>${project.build.directory}/generated/swagger/admin/swagger.json</inputSpec>
This and other `inputSpec` seem to be flipped, so
```suggestion
              <inputSpec>${project.build.directory}/generated/swagger/public/swagger.json</inputSpec>
```

2020-10-01 17:11 UTC, itzg commented on pom.xml
> +              <inputSpec>${project.build.directory}/generated/swagger/public/swagger.json</inputSpec>
and
```suggestion
              <inputSpec>${project.build.directory}/generated/swagger/admin/swagger.json</inputSpec>
```

2020-10-01 18:22 UTC, itzg reviewed
The first commit https://github.com/racker/salus-telemetry-monitor-management/pull/211/commits/ca6766ccfa42860a7c481426736170b4afcab926 addressed my comment, but you flipped it all around in the second commit https://github.com/racker/salus-telemetry-monitor-management/pull/211/commits/dc0d5cd03104898d9c777be1866b636997498825.

What was the reason for the second commit? I'm asking since I'd prefer the diff to be minimal on the other modules.

2020-10-01 23:14 UTC, GeorgeJahad commented on pom.xml
> +              <inputSpec>${project.build.directory}/generated/swagger/admin/swagger.json</inputSpec>
on line 323 the id, is 
```            generate-html-admin
```
I'm assuming @shabd67 is just trying to make it consisent, (so that 'generate-html-admin') actually does generate the admin html.

2020-10-02 13:28 UTC, itzg approved these changes

2020-10-02 13:28 UTC, itzg commented on pom.xml
> +              <inputSpec>${project.build.directory}/generated/swagger/admin/swagger.json</inputSpec>
Thanks! That line was just outside the default diff view, so I didn't have that point of reference.

2020-10-02 15:15 UTC, GeorgeJahad approved these changes

2020-10-05 07:35 UTC, merged