Added paged retrieval approach to get larger BMs
racker/salus-telemetry-monitor-management pull request #219
Opened 2020-10-13 17:01 UTC by rohitsngh27

# Resolves
https://jira.rax.io/browse/SALUS-1031

# What
Added paged retrieval approach to get larger BMs

# How
Used paged traversal for retrieving large BMs and delete them.

# How to test
This can be tested via Junit and Rest call.

# Why
This approach seems to resolve the OOM error issue and speed up the deleting process too.

2020-10-13 22:18 UTC, jjbuchan requested changes
A couple of minor points.

2020-10-13 22:18 UTC, jjbuchan commented on src/test/java/com/rackspace/salus/monitor_management/services/MonitorManagementPolicyTest.java
> +import org.springframework.data.domain.Range.Bound;
This is unused.

2020-10-13 22:18 UTC, jjbuchan commented on src/test/java/com/rackspace/salus/monitor_management/services/MonitorManagementTest.java
> +        .thenReturn(new PageImpl<>(Collections.singletonList(b))).thenReturn(Page.empty());
```suggestion
    when(boundMonitorRepository.findAllByTenantIdAndMonitor_IdIn(anyString(), any(), any()))
        .thenReturn(new PageImpl<>(Collections.singletonList(b)))
        .thenReturn(Page.empty());
```

Can you switch it to this so its a little clearer that multiple returns are being used.

2020-10-14 14:28 UTC, itzg commented on src/test/java/com/rackspace/salus/monitor_management/services/MonitorManagementTest.java
> +    b.setEnvoyId("e-goner");
No need to change, but FYI we have lombok's chainable setters enabled, so you can save a few characters using:
```suggestion
    BoundMonitor b = new BoundMonitor()
      .setMonitor(monitor)
      .setResourceId("r-1")
      .setEnvoyId("e-goner");
```

2020-10-14 14:28 UTC, itzg commented on src/test/java/com/rackspace/salus/monitor_management/services/MonitorManagementTest.java
> +    verify(boundMonitorRepository).findAllByTenantIdAndMonitor_IdIn(any(), any(), any());
I guess we missed this in the original PR for this code. Can you try changing these to exact argument matchers? That might be why you added the `monitorIds` extraction above?

2020-10-14 14:34 UTC, rohitsngh27 commented on src/test/java/com/rackspace/salus/monitor_management/services/MonitorManagementTest.java
> +    verify(boundMonitorRepository).findAllByTenantIdAndMonitor_IdIn(any(), any(), any());
Ohh, Got it now

2020-10-14 14:36 UTC, itzg commented on src/test/java/com/rackspace/salus/monitor_management/services/MonitorManagementTest.java
> +    List<UUID> monitorIds = result.get()
`monitorIds` doesn't seem to be used. (That's what I meant in comment below.)

2020-10-14 16:47 UTC, jjbuchan approved these changes

2020-10-14 16:49 UTC, merged