Added handling for such in effect policies whose monitor is not found while deleting cloned monitor
racker/salus-telemetry-monitor-management pull request #220
Opened 2020-10-16 09:03 UTC by shabd67

# Resolves

[SALUS-1024](https://jira.rax.io/browse/SALUS-1024)

# What

Added handling for such in effect policies whose monitor is not found while deleting cloned monitor

2020-10-16 15:36 UTC, itzg requested changes

2020-10-16 15:36 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
> +    } catch(Exception e)  {
Similar to other comment, catching `Exception` is too broad. Where was the exception happening and what exactly?

2020-10-16 16:37 UTC, jjbuchan requested changes

2020-10-16 16:37 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
> +      } catch(NullPointerException e)  {
Yeah, this logic isn't quite right.  we want to ignore `null` monitorIds.  An exception should never be thrown/caught.

2020-10-16 18:07 UTC, jjbuchan requested changes
A test case should be added for this

2020-10-16 18:07 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
> +      monitorRepository.save(clonedMonitor);
With the recent change is all this idented wrong now?  In IntelliJ you can use the `Code->Auto Indent Lines` option to fix it.

2020-10-19 14:38 UTC, itzg requested changes
I'm still a little confused about the original issue. Speaking of which, please add a unit test that recreates the issue and confirms with code change that it is resolved.

2020-10-19 14:38 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
> +        .filter(p -> event.getMonitorId() != null)
Since `event` is scoped at the method level, it seems more efficient and logical to assert `event.getMonitorId()` before this stream and just build an empty `newPolicyIds`.

2020-10-19 14:38 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
>          .filter(p -> p.getMonitorId().equals(monitorId))
...or could use the null-safe approach and avoid the need for the added filter above
```suggestion
        .filter(p -> Objects.equals(p.getMonitorId(), monitorId))
```

2020-10-19 14:38 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
>          .filter(p -> p.getMonitorId().equals(monitorId))
Comparing with your previous change...was this the line where the exception was thrown?

2020-10-19 14:52 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
>          .filter(p -> p.getMonitorId().equals(monitorId))
In that case `p` must be null since `.equals` evaluates to false when passed a null parameter. I just tested with this code where it prints `result=false`:

```
    String other = null;
    boolean result = "hello".equals(other);
    System.out.println("result="+result);
```

2020-10-19 14:53 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
>          .filter(p -> p.getMonitorId().equals(monitorId))
...you could use [Objects.equals](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Objects.html#equals(java.lang.Object,java.lang.Object)) to be fully null-safe

2020-10-19 15:05 UTC, shabd67 commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
>          .filter(p -> p.getMonitorId().equals(monitorId))
its p.getMonitorId() returning null. 

`String other = null;
	    boolean result = other.equals("hello");
	    System.out.println("result="+result);`

2020-10-19 15:17 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
>          .filter(p -> p.getMonitorId().equals(monitorId))
Why did you add the filter on `event.getMonitorId() != null` then? It seems like that should have been `p.getMonitorId() != null`. In any case, sounds like `Objects.equals` solve that bit.

2020-10-19 16:02 UTC, jjbuchan requested changes
I'm holding off reviewing fully until a test case is added.

The test case should reveal if you have any new bugs.

2020-10-22 12:25 UTC, shabd67 commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
>          .filter(p -> p.getMonitorId().equals(monitorId))
yes, that was incorrect.

2020-10-22 13:22 UTC, itzg requested changes

2020-10-22 13:22 UTC, itzg commented on src/test/java/com/rackspace/salus/monitor_management/services/MonitorManagementPolicyTest.java
> +   * null as monitor id
It would be good to document here the root cause of why a monitor policy had a null monitor ID in the first place. James can probably help provide some input, if needed.

2020-10-22 13:22 UTC, itzg commented on src/test/java/com/rackspace/salus/monitor_management/services/MonitorManagementPolicyTest.java
> +    doReturn(list).when(policyApi).getEffectiveMonitorPoliciesForTenant(anyString(), anyBoolean());
Mockito recommends not using `doReturn` except in rare cases

https://javadoc.io/static/org.mockito/mockito-core/3.5.15/org/mockito/Mockito.html#doReturn-java.lang.Object-
```suggestion
    when(policyApi.getEffectiveMonitorPoliciesForTenant(anyString(), anyBoolean())
      .thenReturn(list);
```

2020-10-22 13:22 UTC, itzg commented on src/test/java/com/rackspace/salus/monitor_management/services/MonitorManagementPolicyTest.java
> +    doReturn(Page.empty()).when(boundMonitorRepository).findAllByTenantIdAndMonitor_IdIn(tenantId, List.of(clonedMonitor.getId()), pageRequest);
and here

2020-10-22 13:22 UTC, itzg commented on src/test/java/com/rackspace/salus/monitor_management/services/MonitorManagementPolicyTest.java
> +    assertTrue(monitorRepository.findByTenantIdAndPolicyId(tenantId, policyId).isEmpty());
Be sure to follow the pattern of assertions in the same test class. This class uses `assertThat` with hamcrest matchers, so this would be
```suggestion
    assertThat(monitorRepository.findByTenantIdAndPolicyId(tenantId, policyId), hasSize(0));
```

2020-10-22 13:22 UTC, itzg commented on src/test/java/com/rackspace/salus/monitor_management/services/MonitorManagementPolicyTest.java
> +  }
Please balance all `when`'s with a `verify`. Also needs a `verifyNoMoreInteractions`.

2020-10-22 14:13 UTC, shabd67 commented on src/test/java/com/rackspace/salus/monitor_management/services/MonitorManagementPolicyTest.java
> +   * null as monitor id
@jjbuchan , have updated the description for this test case. kindly provide your input onto that.

2020-10-22 16:11 UTC, jjbuchan requested changes

2020-10-22 16:11 UTC, jjbuchan commented on src/test/java/com/rackspace/salus/monitor_management/services/MonitorManagementPolicyTest.java
> +        .setId(policyId));
To test the issue you saw, this list should return multiple items.  The policy with the null monitorId should already not have any monitor stored for it.

The test case should verify that removing a previously configured policy monitor works despite the fact another unrelated policy has a null monitor.

2020-10-22 16:11 UTC, jjbuchan commented on src/test/java/com/rackspace/salus/monitor_management/services/MonitorManagementPolicyTest.java
> +   * that was previously using the policy but the monitor is not found
This doesn't quite describe the scenario of this test case enough.

Rather than discussing it more with you right now, I would like you to dig in to try and understand this case and the original problem a little more.  I suspect the more you dig into it to understand things yourself the more you'll learn/remember vs. me just telling you the answer.

Since you'll be doing a few Policy related issues it really will be good to fully understand what's going on.

2020-10-26 15:25 UTC, itzg reviewed
Latest changes address most of my concerns, but I'll let James provide more specific feedback.

2020-10-26 15:32 UTC, jjbuchan commented on src/test/java/com/rackspace/salus/monitor_management/services/MonitorManagementPolicyTest.java
> +  public void testHandleMonitorPolicyEvent_removePolicy_null_monitor_id() {
With this comment I meant that it was good to keep this test as is (other than changing the comment) but then add a new test for what I described below.  Can you update this file to include the two new tests rather than just one.

2020-10-26 15:34 UTC, shabd67 commented on src/test/java/com/rackspace/salus/monitor_management/services/MonitorManagementPolicyTest.java
> +  public void testHandleMonitorPolicyEvent_removePolicy_null_monitor_id() {
sure. I am adding that previous test case as well.

2020-10-26 15:44 UTC, jjbuchan requested changes

2020-10-26 15:44 UTC, jjbuchan commented on src/test/java/com/rackspace/salus/monitor_management/services/MonitorManagementPolicyTest.java
> +   * having a null monitor id
This comment isn't very clear.  I'll wait until both tests are up before going into more detail as that'll make it easier to note the differences and if anything is still missing.

2020-10-27 15:58 UTC, jjbuchan approved these changes

2020-10-27 16:05 UTC, merged