Added apis to get detached but pending timeout pollers
racker/salus-telemetry-monitor-management pull request #222
Opened 2020-10-23 12:04 UTC by rohitsngh27

# Resolves
https://jira.rax.io/browse/SALUS-992

# What
Added apis to get detached but pending timeout pollers

# How
Added 2 new apis for public and admin to get the list of detached but pending timeout pollers.

# How to test
This can be tested via Rest call.

2020-10-23 17:04 UTC, itzg requested changes
Great changes especially with the unit tests. Speaking of which, can you add one more unit test for the "tenant wide" private zone call?

2020-10-23 17:07 UTC, rohitsngh27 commented
> Great changes especially with the unit tests. Speaking of which, can you add one more unit test for the "tenant wide" private zone call?

I have added that in line number 794. I guess that's what you are talking about?

2020-10-23 18:02 UTC, itzg commented
> > Great changes especially with the unit tests. Speaking of which, can you add one more unit test for the "tenant wide" private zone call?
> 
> I have added that in line number 794. I guess that's what you are talking about?

I'm sorry, I didn't notice there were two cases in one. Thanks!

2020-10-23 18:02 UTC, itzg approved these changes

2020-10-23 18:58 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/monitor_management/web/controller/ZoneApiController.java
> +  @GetMapping("/admin/detached-pollers/**")
Following on from this thread - https://github.com/racker/salus-telemetry-zone-watcher/pull/24#discussion_r510354354

I'm not sure why we're limiting the endpoint to detached pollers and not using it to query all pollers?

2020-10-24 11:33 UTC, rohitsngh27 commented on src/main/java/com/rackspace/salus/monitor_management/web/controller/ZoneApiController.java
> +  @GetMapping("/admin/detached-pollers/**")
As mentioned by @itzg in here :- https://github.com/racker/salus-telemetry-monitor-management/blob/d241afc0d4be2e6269a41d9a3126730fe66c2086/src/main/java/com/rackspace/salus/monitor_management/web/controller/ZoneApiController.java#L137 
This gives us the count of connected pollers with some more details I guess.

2020-10-26 16:47 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/monitor_management/web/controller/ZoneApiController.java
> +  @GetMapping("/admin/detached-pollers/**")
I see `/zone-assignment-counts/{name}` returns items in this format:

```
[
  {
    "resourceId": "r-1",
    "envoyId": "e-1",
    "assignments": 3
  }
]
```

and `/detached-pollers/{name}` returns a list of resource strings.

I do still wonder if these two endpoints should be combined.

We could update the original object to contain a `status` field to show `connected` and `expiring` or something like that and be able to filter on what we want to see.

I think the `expiring` pollers would also have an `assignments` value until they have fully disconnected.  

@itzg wouldn't we want to know how many monitors are assigned to an `expiring` poller the same way we do for an `active` one?  Is that info not being available not part of the problem we have right now?

2020-10-26 17:40 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/web/controller/ZoneApiController.java
> +  @GetMapping("/admin/detached-pollers/**")
`/zone-assignment-counts` will include the pending-expiring ones also since it merges the information from both etcd (where they'd be absent) and the bound monitors table (where they'd be present).

> Is that info not being available not part of the problem we have right now?

I don't know of any remaining problem. Last known problems I knew about were fixed in https://github.com/racker/salus-telemetry-monitor-management/pull/205 and https://github.com/racker/salus-telemetry-monitor-management/pull/208

2020-10-26 17:43 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/web/controller/ZoneApiController.java
> +  @GetMapping("/admin/detached-pollers/**")
...BTW the original purpose of this issue was simply to help QE verify the test case dealing with stopping/starting envoy-pollers and avoid having to query etcd directly to confirm the intermediate state.

2020-10-26 17:44 UTC, itzg approved these changes
I'm still good with the changes, but being the original requestor I might be "blind" to a use case that @jjbuchan sees is missing.

2020-10-26 18:26 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/monitor_management/web/controller/ZoneApiController.java
> +  @GetMapping("/admin/detached-pollers/**")
> I don't know of any remaining problem

I really mean "missing feature" vs. "problem".

> the original purpose of this issue was simply to help QE verify the test case dealing with stopping/starting envoy-pollers and avoid having to query etcd directly to confirm the intermediate state.

The problem I'm having with these changes is that if an endpoint already exists that knows (or at least can know) all the info why are we adding a completely separate one vs. just enhancing the original?

It sounds like adding a `status`/`state` field to the existing endpoint and adding filtering via query parameters solves QE's need?

My concerns are from a usability/training/maintenance perspective.  Why have two endpoints that return things in different formats when we can have one that does everything and returns things in a consistent manner.

2020-10-26 18:55 UTC, itzg commented
> It sounds like adding a status/state field to the existing endpoint and adding filtering via query parameters solves QE's need?

This sounds like a reasonable compromise, but rather than keep dragging this out for @rohitsngh27 we should go back to the drawing board and write up clear requirements.

2020-10-26 19:04 UTC, itzg commented
...and by "we" I mean I'll add a comment to the Jira issue that we can iterate upon with the requirements.

2020-10-27 11:27 UTC, rohitsngh27 commented
How should I proceed with this PR now? Do I need to make any changes or merge it as is?

2020-10-27 13:26 UTC, itzg commented
> How should I proceed with this PR now? Do I need to make any changes or merge it as is?

I think you can use this PR to convey the next iteration since the changes should remain mostly in the same areas of code.

@jjbuchan @rohitsngh27 , I was hoping gist's allowed for inline comments, but they don't so maybe adding comments at the bottom of https://gist.github.com/itzg/d334f9b3aea2e03e055fad71a5de2ff4 could be a way to review the new requirements.

2020-10-27 13:30 UTC, rohitsngh27 commented
> I think you can use this PR to convey the next iteration since the changes should remain mostly in the same areas of code.

So, Should I make the changes in existing `getPrivateZoneAssignmentCounts` and `getPublicZoneAssignmentCounts` as mentioned by @jjbuchan ?

2020-10-28 11:25 UTC, rohitsngh27 commented
Initial commit with new changes to check if it's fine. Will update/add unit test cases later

2020-10-28 15:02 UTC, itzg requested changes
Looking good overall

2020-10-28 15:02 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/web/controller/ZoneApiController.java
> +      @PathVariable String tenantId, @PathVariable @PrivateZoneName Optional<String> name) {
I think this shouldn't be `Optional` since there's now the separate `getPrivateZoneAssignmentCountsPerTenant`

2020-10-28 15:20 UTC, rohitsngh27 commented on src/main/java/com/rackspace/salus/monitor_management/services/ZoneAllocationResolver.java
> +          if (!activePollerResources.isEmpty()) {
Actually for the case when lets say an envoy with Zone-> `zone1` and Resource-> `resource1`and the envoy is currently in expiring stage(pending timeout).
So, Ideally the response should only show the `connected=false` one but if I remove the empty check from here it gets the data from BoundMonitor where it would be present and set that into the map for activePollersCount.

2020-10-28 17:00 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/services/ZoneAllocationResolver.java
> +          if (!activePollerResources.isEmpty()) {
That makes sense for `retrieveExpiredPollerResourceCounts` where it is returning only `connected=false` ones, but for `retrieveActivePollerResourceCounts` it seems like it should always consider the bound monitors counts via SQL.

2020-10-28 17:06 UTC, rohitsngh27 commented on src/main/java/com/rackspace/salus/monitor_management/services/ZoneAllocationResolver.java
> +          if (!activePollerResources.isEmpty()) {
So an envoy is connected it will show 2 same entry in final response with difference being connected = true and false like:-
`[
  {
    "resourceId": "test11",
    "envoyId": "1fa0b59e-193b-11eb-a876-acde48001122",
    "assignments": 20,
    "connected": true
  },
  {
    "resourceId": "test11",
    "envoyId": "1fa0b59e-193b-11eb-a876-acde48001122",
    "assignments": 20,
    "connected": false
  }
]`

2020-10-28 17:09 UTC, rohitsngh27 commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
> +              zoneAllocationResolver.getExpiredZoneBindingCounts(zone).join(), false));
`thenAccept` will return void but I need the result for `zoneAllocationResolver.getExpiredZoneBindingCounts(zone)` to add to the final list response.

2020-10-28 17:10 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/services/ZoneAllocationResolver.java
> +          if (!activePollerResources.isEmpty()) {
Thanks, that helped to clarify. I was mainly concerned about breaking the bound monitor processing, but I'm now thinking even for that it should only consider active envoy-pollers anyway.

2020-10-28 17:12 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
> +              zoneAllocationResolver.getExpiredZoneBindingCounts(zone).join(), false));
Sorry, I meant `thenCompose`

2020-10-28 17:14 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/monitor_management/services/ZoneAllocationResolver.java
> +          if (!activePollerResources.isEmpty()) {
This conversation is confusing me.  I'm going to keep going through the rest of the code and come back to this, but so far I'm not sure if I agree with

> for `retrieveActivePollerResourceCounts` it seems like it should always consider the bound monitors counts via SQL.

2020-10-28 17:14 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/monitor_management/web/controller/ZoneApiController.java
> +    String zoneName = name.orElse("");
Adding a note to remind myself to come back and look at this.

Based on the above comment, this logic should change.

2020-10-28 17:14 UTC, jjbuchan commented on src/test/java/com/rackspace/salus/monitor_management/web/controller/ZoneApiControllerTest.java
> +            get("/api/admin/detached-pollers/{name}",
Looks like tests still need to be updated.

2020-10-28 17:16 UTC, rohitsngh27 commented on src/test/java/com/rackspace/salus/monitor_management/web/controller/ZoneApiControllerTest.java
> +            get("/api/admin/detached-pollers/{name}",
I will update all the tests. Right now only focusing on functionality first

2020-10-28 17:45 UTC, rohitsngh27 commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
> +      if (!assignmentCounts.isEmpty()) {
If I remove this it does show all the zones but ones having no envoys attached will come as empty array

2020-10-28 18:30 UTC, rohitsngh27 commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
> +  public CompletableFuture<Map<String, List<ZoneAssignmentCount>>> getAssignmentCountForTenant(
Any reference on this one? 
I was thinking of first all all the completable future returning from `getZoneAssignmentCounts ` in a list of completable future and then using `CompletableFuture.allOf`.
But this approach is making code more complex as we also need to take care of the key(zone name) which will be used in final response map

2020-10-28 18:32 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
> +      if (!assignmentCounts.isEmpty()) {
Cool.  I think that's what I'd expected.

2020-10-28 18:36 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
> +  public CompletableFuture<Map<String, List<ZoneAssignmentCount>>> getAssignmentCountForTenant(
Yeah, merging all those completables into the final map will indeed get complicated. I'm definitely fine with how you have it.

2020-10-29 11:27 UTC, rohitsngh27 commented
Resolved comments and added unit test cases too

2020-10-29 11:41 UTC, rohitsngh27 commented on src/main/java/com/rackspace/salus/monitor_management/services/ZoneAllocationResolver.java
> +          if (!activePollerResources.isEmpty()) {
Do I need to remove the empty check here in both active or expired one?

2020-10-29 16:19 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/monitor_management/services/ZoneAllocationResolver.java
> +          if (!activePollerResources.isEmpty()) {
From what I understand I think it should stay.

2020-10-29 16:46 UTC, jjbuchan reviewed
Sorry to drag this out a little more but if you can look through all the methods used here and tweak the javadoc where needed that'll help the next person who has to look at this code.

Thanks!

2020-10-29 16:46 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
>      ZoneAllocationResolver zoneAllocationResolver = zoneAllocationResolverFactory.create();
I can't add a comment high enough up, but can you add some javadoc to this method?

2020-10-29 16:46 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
> +  public List<ZoneAssignmentCount> getZoneAssignmentPollerCount(
This javadoc maybe needs to be expanded?

We have `getZoneAssignmentCounts` and `getZoneAssignmentPollerCount` and it's not immediately clear what the difference is without looking through the code in each.

2020-10-29 16:46 UTC, jjbuchan commented on src/test/java/com/rackspace/salus/monitor_management/services/MonitorManagement_ZoneBindingsTest.java
> +        .thenReturn(new PageImpl<>(List.of("z-1", "z-2")));
If we add a `z-3` in here will it simulate a zone connected with no pollers and therefore show as an empty list?

An assertion on `counts.get("z-3")` isEmpty or hasSize(0) would be good to cover that scenario.

2020-10-29 16:46 UTC, jjbuchan commented on src/test/java/com/rackspace/salus/monitor_management/web/controller/ZoneApiControllerTest.java
> +            "z-3", Collections.emptyList());
Ah yeah, this is the scenario I'm talking about above.  I think the above changes might need to be done to ensure this mock is accurate.

2020-10-29 16:49 UTC, rohitsngh27 commented on src/test/java/com/rackspace/salus/monitor_management/services/MonitorManagement_ZoneBindingsTest.java
> +        .thenReturn(new PageImpl<>(List.of("z-1", "z-2")));
I have used a json file where `z-3` is set to empty list. That would cover this I guess?

2020-10-29 16:52 UTC, jjbuchan commented on src/test/java/com/rackspace/salus/monitor_management/services/MonitorManagement_ZoneBindingsTest.java
> +        .thenReturn(new PageImpl<>(List.of("z-1", "z-2")));
Not quite.  That is testing a different layer of the service.

In that test you are mocking the response from monitorManagement.

```
        when(monitorManagement.getZoneAssignmentCountForTenant(any()))
            .thenReturn(CompletableFuture.completedFuture(expected));
```

I'm suggesting we add the empty `z-3 ` to this test as that will verify the above `when` assumption is correct.

2020-10-29 17:03 UTC, rohitsngh27 commented on src/test/java/com/rackspace/salus/monitor_management/services/MonitorManagement_ZoneBindingsTest.java
> +        .thenReturn(new PageImpl<>(List.of("z-1", "z-2")));
Ohhhh Got it... You mean to add the case when zone has no pollers(active or expiring).

2020-10-29 17:03 UTC, rohitsngh27 commented on src/test/java/com/rackspace/salus/monitor_management/web/controller/ZoneApiControllerTest.java
> +            "z-3", Collections.emptyList());
This one is fine. Right?

2020-10-29 17:04 UTC, jjbuchan commented on src/test/java/com/rackspace/salus/monitor_management/services/MonitorManagement_ZoneBindingsTest.java
> +        .thenReturn(new PageImpl<>(List.of("z-1", "z-2")));
Yep, that's it

2020-10-29 17:04 UTC, jjbuchan commented on src/test/java/com/rackspace/salus/monitor_management/web/controller/ZoneApiControllerTest.java
> +            "z-3", Collections.emptyList());
yeah, all good here.  just noticed it was related to the one i was talking about above.

2020-10-29 17:27 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
> +  public List<ZoneAssignmentCount> mapToZoneAssignmentCount(
One final thing!  Looks like this method could be package private?  In addition to the updated javadoc I think that would help show this is more of a helper method than something that is called directly by other services.

```suggestion
  List<ZoneAssignmentCount> mapToZoneAssignmentCount(
```

2020-10-29 17:28 UTC, rohitsngh27 commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
> +  public List<ZoneAssignmentCount> mapToZoneAssignmentCount(
Ohh yes, Sorry to miss out on that.

2020-10-29 17:36 UTC, jjbuchan approved these changes
Thanks for putting up with all the comments!

2020-10-29 17:37 UTC, itzg approved these changes

2020-10-29 17:37 UTC, itzg commented on src/test/java/com/rackspace/salus/monitor_management/services/MonitorManagement_ZoneBindingsTest.java
> +        .thenReturn(CompletableFuture.completedFuture(Collections.emptyMap()));
This approach is fine since the ordering is ensured by previous mock response, but FYI you can always use exact argument matchers on `when` declarations to narrow the mock response for each.

2020-10-29 17:38 UTC, rohitsngh27 commented on src/test/java/com/rackspace/salus/monitor_management/services/MonitorManagement_ZoneBindingsTest.java
> +        .thenReturn(CompletableFuture.completedFuture(Collections.emptyMap()));
I was doing that way only first but somehow it was not working and giving null pointer in original code where the mocked method is called.

2020-10-29 17:41 UTC, itzg commented on src/test/java/com/rackspace/salus/monitor_management/services/MonitorManagement_ZoneBindingsTest.java
> +        .thenReturn(CompletableFuture.completedFuture(Collections.emptyMap()));
Strange. Maybe the argument matching equality wasn't quite as expected. Again, what you have is fine and thanks for trying the other way initially.

2020-10-29 18:03 UTC, merged