Rename PolicyMonitor to MonitorTemplate
racker/salus-telemetry-monitor-management pull request #224
Opened 2020-10-28 13:46 UTC by shabd67

# Resolves

[SALUS-1035](https://jira.rax.io/browse/SALUS-1035)

# What

Renamed PolicyMonitor to MonitorTemplate

2020-10-28 16:49 UTC, itzg reviewed
It's outside the diff range, so I couldn't add a comment there: it seems like changing the request mapping paths like `/tenant/{tenantId}/policy-monitors` was important too.

Also, is this PR ready for full review? It's marked as draft.

2020-10-28 17:17 UTC, shabd67 commented
> It's outside the diff range, so I couldn't add a comment there: it seems like changing the request mapping paths like `/tenant/{tenantId}/policy-monitors` was important too.
> 
> Also, is this PR ready for full review? It's marked as draft.

Yes, changing the request mapping paths in monitor-management along with public/admin apis part is still left. I wasn't sure about the changes to be done. Hence, created a draft PR. If its fine then will go ahead with other changes as well.

2020-10-29 21:21 UTC, itzg reviewed
Just some minor phrasing question/comments.

2020-10-29 21:21 UTC, itzg commented on src/test/java/com/rackspace/salus/monitor_management/web/controller/MonitorApiControllerTest.java
> +
Can be deleted?

2020-10-29 21:21 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
> +  public Optional<Monitor> getMonitorUsingTemplatesForTenant(UUID uuid, String tenantId) {
Seems like this method name doesn't need to reference "templates" and is more like `getMonitorForTenant`...which then makes me realize this method is probably redundant with `Optional<Monitor> getMonitor(String tenantId, UUID id)`

which I'm

2020-10-29 23:26 UTC, jjbuchan requested changes
This looks good.  Just a couple small comments.

I'm assuming there's more PRs on the way for policy-management and docs?

2020-10-29 23:26 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
> +  }
This method is a duplicate of `getMonitor`.  `getMonitor` can be used in any places you've used this.

2020-10-29 23:26 UTC, jjbuchan commented on src/test/java/com/rackspace/salus/monitor_management/web/controller/MonitorApiControllerTest.java
> +//    verifyNoMoreInteractions(monitorManagement);
Need to remove this commented out section?

2020-10-29 23:26 UTC, jjbuchan commented on src/test/java/com/rackspace/salus/monitor_management/web/controller/MonitorApiControllerTest.java
> +//    verifyNoMoreInteractions(monitorManagement);
Or remove the block below and uncomment this?

2020-10-29 23:26 UTC, jjbuchan commented on src/test/java/com/rackspace/salus/monitor_management/web/controller/MonitorApiControllerTest.java
> +//    verifyNoMoreInteractions(monitorManagement);
Fyi, for debugging these kind of tests it can also be good to add a `.andDo(print())` into the `perform` request.  You'll see we have that in place on server of the controller tests.  It allows you to see the full result of the request instead of using `System.out.println` on individual parts.

2020-10-29 23:28 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
> +  public Optional<Monitor> getMonitorUsingTemplatesForTenant(UUID uuid, String tenantId) {
Not sure why your comments weren't showing up for me as I reviewed it.  Ended up duplicating a couple

2020-10-29 23:32 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/monitor_management/web/controller/MonitorApiController.java
> +  @ApiOperation(value = "Gets all Monitors using templates for Tenant")
I think this is fine.  If I'm understanding your point correctly the difference is that you view "Monitor Templates" via the admin api call.  That call is returning the template that is not actually running anywhere - it's just a placeholder waiting to be cloned.

Once it is cloned to a tenant that new object is no longer a template, it's a real monitor just like all the others for that tenant.  The only difference it was created based on a template and remains tied to that template.  It is these cloned monitors or "monitors using templates" that is returned by the public api call.

2020-10-30 08:28 UTC, shabd67 commented on src/test/java/com/rackspace/salus/monitor_management/web/controller/MonitorApiControllerTest.java
> +//    verifyNoMoreInteractions(monitorManagement);
noted. will take care of that.

2020-10-30 13:10 UTC, shabd67 commented
> This looks good. Just a couple small comments.
> 
> I'm assuming there's more PRs on the way for policy-management and docs?

@jjbuchan , do I need to make changes in policy-management as well? I think policy-management is responsible for monitor or metadata policy, not policy-monitor.

2020-10-30 13:44 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/web/controller/MonitorApiController.java
> +  @ApiOperation(value = "Gets all Monitors using templates for Tenant")
In that case it is adding to the confusion to use the same API path segment `/monitor-templates` to refer to both "monitor templates" (via admin API) and "monitor using template" (via public API).

2020-10-30 14:56 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/monitor_management/web/controller/MonitorApiController.java
> +  @ApiOperation(value = "Gets all Monitors using templates for Tenant")
Ah yes, I think I overlooked that.  I'd say we should get rid of this endpoint.  @shabd67 can you confirm it's not used by anything and then remove it from here and the public api?

Similar to what Rohit was working on, I think if we want to filter based on using policy or not, we can add a query parameter to the main `/monitors` endpoint.

2020-10-30 15:04 UTC, shabd67 commented on src/main/java/com/rackspace/salus/monitor_management/web/controller/MonitorApiController.java
> +  @ApiOperation(value = "Gets all Monitors using templates for Tenant")
its not being used anything. 

we should remove below endpoint as well, na?
`
  @GetMapping("/tenant/{tenantId}/monitor-templates/{uuid}")
  @ApiOperation(value = "Gets Monitor using template for Tenant")
`

2020-10-30 15:30 UTC, jjbuchan commented
@shabd67 I see several uses in policy-management:

<img width="692" alt="image" src="https://user-images.githubusercontent.com/4358210/97724309-5d6e7700-1a92-11eb-9027-a8c0f52805f4.png">


...and based on that there should be more changes in this PR as well because the names of the APIs used will be updated.

2020-10-30 15:32 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/monitor_management/web/controller/MonitorApiController.java
> +  @ApiOperation(value = "Gets all Monitors using templates for Tenant")
Yes

2020-10-30 15:33 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/monitor_management/web/controller/MonitorApiController.java
> +  @ApiOperation(value = "Gets all Monitors using templates for Tenant")
Both these endpoints were likely leftover from the previous design where policy monitors were not quite the same as a "normal" monitor.

2020-11-05 15:49 UTC, itzg reviewed
Changes look good from my previous review, but we'll let @jjbuchan provide final approval.

2020-11-23 15:13 UTC, itzg approved these changes

2020-11-23 15:28 UTC, merged