Metadata policy is being cashed even after deletion
racker/salus-telemetry-monitor-management pull request #227
Opened 2020-11-04 14:33 UTC by shabd67

# Resolves

[SALUS-1033](https://jira.rax.io/browse/SALUS-1033)

# What

BugFix - Metadata policy is being cashed even after deletion

2020-11-04 15:31 UTC, itzg requested changes
It seems like a unit test should have been impacted by the additional call to `PolicyApi`. Can you double check that? Maybe there's a `verifyNoMoreInteractions` missing on the corresponding unit test.

2020-11-04 15:31 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
> +    policyApi.getEffectiveMonitorMetadataMap(tenantId, event.getTargetClassName(), event.getMonitorType(), false);
Rather than utilizing the "side effect" of the `@CacheEvict` on this method I'd prefer you add and call a specific method called something like `evictEffectiveMonitorMetadataMap` that just has the `@CacheEvict` on it. Admittedly it's an odd fit for the API interface, but will make the intent so much clearer.

2020-11-04 15:51 UTC, shabd67 commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
> +    policyApi.getEffectiveMonitorMetadataMap(tenantId, event.getTargetClassName(), event.getMonitorType(), false);
Should I remove `@CacheEvict ` from `getEffectiveMonitorMetadataMap` if we are using `@CacheEvict` on `evictEffectiveMonitorMetadataMap ` ?

2020-11-04 15:56 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
> +    policyApi.getEffectiveMonitorMetadataMap(tenantId, event.getTargetClassName(), event.getMonitorType(), false);
Have you done a usage search to see if the "use cache" parameter is ever passed as false? If it isn't, then yes, it seems safe/good to remove the annotation and possibly adjust the other on it.

2020-11-04 16:02 UTC, shabd67 commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
> +    policyApi.getEffectiveMonitorMetadataMap(tenantId, event.getTargetClassName(), event.getMonitorType(), false);
yes, checked for "use cache" parameter passed as false, its not there apart from test cases. So, will be safe to delete that annotation from `getEffectiveMonitorMetadataMap`

2020-11-04 16:31 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
> +    policyApi.getEffectiveMonitorMetadataMap(tenantId, event.getTargetClassName(), event.getMonitorType(), false);
Sounds good then. Can also remove the parameter unless that's already what you're thinking. Hopefully the ripple effect of removing the parameter won't cause too many tedious changes to refactor.

2020-11-05 08:44 UTC, shabd67 commented
> It seems like a unit test should have been impacted by the additional call to `PolicyApi`. Can you double check that? Maybe there's a `verifyNoMoreInteractions` missing on the corresponding unit test.

It seems there is no corresponding unit test case for this scenario.

2020-11-09 20:31 UTC, jjbuchan reviewed
> It seems there is no corresponding unit test case for this scenario.

If you see there are no tests for a particular function you should always aim to add some.

---

Once my comments in https://github.com/racker/salus-policy-management/pull/49 are addressed I'd expect there to me some more changes in this PR as well.  Please push changes over there prior to requesting a review over here.

Thanks

2020-11-09 20:44 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
> +    policyApi.evictEffectiveMonitorMetadataMap(tenantId, event.getTargetClassName(), event.getMonitorType());
One other thing... it might be possible to move this line down into the `if (policyOptional.isEmpty()) {` condition.

Can you look into that to see if my thought is correct.

If it is a comment should be added to explain why it is called there.

2020-11-20 15:26 UTC, itzg reviewed
Address all comments

2020-11-20 15:26 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
> +    policyApi.evictEffectiveMonitorMetadataMap(tenantId, event.getTargetClassName(), event.getMonitorType());
You **must** reply to all PR comments explaining why you won't make the change or what change you plan. PR's will not be approved with unanswered comments.

2020-11-20 15:50 UTC, shabd67 commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
> +    policyApi.evictEffectiveMonitorMetadataMap(tenantId, event.getTargetClassName(), event.getMonitorType());
I think reverse should be applicable i.e. if the policy is relevant to this tenant, in that case we should remove it from cache. So irrespective of that, I have removed that entry from cache whether that policy is applicable for that tenant or not.

2020-11-20 15:53 UTC, itzg commented on src/main/java/com/rackspace/salus/monitor_management/services/MonitorManagement.java
> +    policyApi.evictEffectiveMonitorMetadataMap(tenantId, event.getTargetClassName(), event.getMonitorType());
That's reasonable. Thanks.

2020-11-20 15:53 UTC, itzg approved these changes

2020-11-23 16:21 UTC, merged